# -*- coding: utf-8 -*-
"""Quiz game micro it project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cg7Jihr-KJ-BFvwEtmJpgFtdsTZp2tTu
"""

def ask_question(question, options, correct_answer):
    print("\n" + question)
    for i, option in enumerate(options, start=1):
        print(f"{i}. {option}")

    try:
        answer = int(input("Your answer (1-4): "))
        if options[answer - 1].lower() == correct_answer.lower():
            print("✅ Correct!")
            return True
        else:
            print(f"❌ Wrong! The correct answer is: {correct_answer}")
            return False
    except (ValueError, IndexError):
        print("Invalid input. Please choose a number from 1 to 4.")
        return False


def quiz_game():
    questions = [
        {
            "question": "What is the capital of France?",
            "options": ["Berlin", "Madrid", "Paris", "Rome"],
            "answer": "Paris"
        },
        {
            "question": "Which planet is known as the Red Planet?",
            "options": ["Earth", "Mars", "Jupiter", "Saturn"],
            "answer": "Mars"
        },
        {
            "question": "Who wrote 'Hamlet'?",
            "options": ["Shakespeare", "Dickens", "Hemingway", "Tolstoy"],
            "answer": "Shakespeare"
        },
        {
            "question": "What is 5 * 6?",
            "options": ["30", "35", "25", "40"],
            "answer": "30"
        }
    ]

    score = 0

    print("🎉 Welcome to the Quiz Game!")
    for q in questions:
        if ask_question(q["question"], q["options"], q["answer"]):
            score += 1

    print(f"\n🏁 Quiz finished! Your score: {score}/{len(questions)}")


if __name__ == "__main__":
    quiz_game()